ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'SHORT_ANSWER';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'ESSAY';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'PROBLEM_SOLVING';

ALTER TABLE "Flashcard" ADD COLUMN "difficulty" "QuizDifficulty" NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "QuizQuestion" ADD COLUMN "difficulty" "QuizDifficulty" NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE "QuizAnswer" ADD COLUMN "scorePercent" DOUBLE PRECISION;
ALTER TABLE "QuizAnswer" ADD COLUMN "feedback" TEXT;
